name: Test Self-Hosted Runner

on:
  push:
    branches:
      - staging
  workflow_dispatch: # Allows manual trigger

jobs:
  test-connectivity:
    runs-on: self-hosted # Use your runner's labels

    steps:
    - name: Simple Echo
      run: echo "Hello from self-hosted runner!"

    - name: Check VM Details
      run: |
        echo "Current User: $(whoami)"
        echo "Current Directory: $(pwd)"
        echo "Node Version: $(node -v)"
        echo "NPM Version: $(npm -v)"
        echo "PM2 Version: $(pm2 -v)"
        echo "PATH: $PATH"  
