name: Deploy Frontend to Staging VM

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted # This targets the Frontend-specific runner

    steps:
    - name: Checkout Frontend code
      uses: actions/checkout@v4

    - name: Install Frontend Dependencies and Build
      run: |
        npm install # Install all dependencies including devDependencies for build
        sudo npm run build # Build your frontend project, creates 'dist' folder
      working-directory: ${{ github.workspace }} # This is the default if not specified

    - name: Clean and Copy Frontend Build to VM Destination
      run: |
        DEPLOY_DIR="/home/azureuser/taotter-interface"
        echo "Clearing old frontend build from ${DEPLOY_DIR}..."
        sudo rm -rf "${DEPLOY_DIR}/dist" # Clean only the dist folder
        sudo mkdir -p "${DEPLOY_DIR}" # Ensure directory exists

        echo "Copying new frontend build from checkout to ${DEPLOY_DIR}..."
        sudo cp -R "${{ github.workspace }}/dist" "${DEPLOY_DIR}/"

    - name: Restart PM2 Frontend Process
      run: |
        echo "Restarting PM2 frontend process..."
        cd /home/azureuser/ # Assuming ecosystem.config.js is here
        pm2 restart taotter-frontend # Make sure this matches your ecosystem.config.js name
        echo "Frontend deployment complete!"
